network:
  ethernets:
    "{{ kvm_bridge_network_interface }}":
      dhcp4: false
      dhcp6: false
  bridges:
    br0:
      interfaces: ["{{ kvm_bridge_network_interface }}"]
      addresses: ["{{ kvm_bridge_network_ip }}"]
      routes:
        - to: default

          via: { { kvm_bridge_network_gateway } }
      mtu: 1500
      nameservers:
        addresses: ["{{ kvm_bridge_network_dns }}"]
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no
  version: 2
# below actually worked

# network:
#   bridges:
#     br0:
#       dhcp4: false
#       interfaces:
#         - eno1
#       addresses:
#       - 192.168.1.9/24
#       routes:
#         - to: default
#           via: 192.168.1.1
#       nameservers:
#         addresses:
#         - 192.168.1.1
#         - 1.1.1.1
#         search: []
#   ethernets:
#     eno1:
#       dhcp4: no
#     eno2:
#       dhcp4: true
#     eno3:
#       dhcp4: true
#     eno4:
#       dhcp4: true
#   version: 2
#
#
